
module_name: "example_sensor_hub"

buckets:
    bucket_0:
        frequency_hz: 100
        parameters:
            # Listed in order of their pins in the sensor hub board side connector
            temp1_C:
                ADC: ADC1_IN11
                sensor: temp_sensor
                samples_buffered: 2
            temp2_C:
                ADC: ADC1_IN12
                sensor: temp_sensor
                samples_buffered: 2
            temp3_C:
                ADC: ADC1_IN13
                sensor: temp_sensor
                samples_buffered: 2
            temp4_C:
                ADC: ADC1_IN10
                sensor: temp_sensor
                samples_buffered: 2
            temp5_C:
                ADC: ADC1_IN15
                sensor: temp_sensor
                samples_buffered: 2
            temp6_C:
                ADC: ADC1_IN7
                sensor: temp_sensor
                samples_buffered: 2
            temp7_C:
                ADC: ADC1_IN6
                sensor: temp_sensor
                samples_buffered: 2
            temp8_C:
                ADC: ADC1_IN14
                sensor: temp_sensor
                samples_buffered: 2
            flowRate1_GPerSec:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 2


