
module_name: "example_sensor_hub"

buckets:
    bucket_0:
        frequency_hz: 100
        parameters:
            # Listed in order of their pins in the sensor hub board side connector
            pressure1_psi:
                ADC: ADC1_IN11
                sensor: pressure_sensor_absolute
                samples_buffered: 2
            pressure2_psi:
                ADC: ADC1_IN12
                sensor: pressure_sensor_absolute
                samples_buffered: 2
            pressure3_psi:
                ADC: ADC1_IN13
                sensor: pressure_sensor_absolute
                samples_buffered: 2
            pressure4_psi:
                ADC: ADC1_IN10
                sensor: combined_pressure_sensor
                samples_buffered: 2
            pressure5_psi:
                ADC: ADC1_IN15
                sensor: pressure_sensor_absolute
                samples_buffered: 2
            pressure6_psi:
                ADC: ADC1_IN7
                sensor: pressure_sensor_absolute
                samples_buffered: 2
            pressure7_psi:
                ADC: ADC1_IN6
                sensor: pressure_sensor_absolute
                samples_buffered: 2
            pressure8_psi:
                ADC: ADC1_IN14
                sensor: pressure_sensor_absolute
                samples_buffered: 2
            flowRate2_Hz:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 2

